### ISSUE TITLE
Crash on PWMEGeoZoneManager locationManagerDidUpdateLocations

### ISSUE THREAD

**Issue by harishios** [phunware/maas-location-ios-sdk#38]
Hi Team,

We got a Crash on PWEngagement SDK in the following method,

`PWEngagement | -[PWMEGeoZoneManager locationManagerDidUpdateLocations:]`

Attaching more stack trace for reference,

`Crashed: com.apple.root.default-qos 0 libobjc.A.dylib 0x19709bbf0 objc_retain + 16 1 PWEngagement 0x10236bbd0 -[PWMEGeoZoneManager locationManagerDidUpdateLocations:] + 96 2 PWEngagement 0x102362350 __65-[PWMELocationUpdatesManager locationManager:didUpdateLocations:]_block_invoke + 704 3 libdispatch.dylib 0x1978e8a38 _dispatch_call_block_and_release + 24 4 libdispatch.dylib 0x1978e97d4 _dispatch_client_callout + 16 5 libdispatch.dylib 0x19788dc7c _dispatch_queue_override_invoke + 684 6 libdispatch.dylib 0x19789a02c _dispatch_root_queue_drain + 372 7 libdispatch.dylib 0x19789a8d0 _dispatch_worker_thread2 + 128 8 libsystem_pthread.dylib 0x197ac91b4 _pthread_wqthread + 464 9 libsystem_pthread.dylib 0x197acbcd4 start_wqthread + 4`

**PWLocationVersion = @"3.8.0";
PWEngagementVersion = @"3.7.3";**

**Comment by ghost** [comment]
Closing, as this is specific to the Engagement SDK (which doesn't use the Location SDK).
